### ISSUE TITLE
Possible data fixes

### ISSUE THREAD

**Issue by jd-coderepos** [Kabongosalomon/task-dataset-metric-nli-extraction#1]
In the following file https://github.com/Kabongosalomon/task-dataset-metric-nli-extraction/blob/main/data/annotations_merged/resultsAnnotation.tsv, please see lines 3149 and 3150 which are as follows:

(1080Ti)	

(1080Ti)

**Comment by Kabongosalomon** [comment]
Hi @jd-coderepos great catch, I will take care of it, thank you. 

We technically made sure programmatically not to consider these kinds of noise in the data.
